name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  run_tests:

    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        python: ['3.10']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade setuptools
        run: |
          pip3 install wheel --upgrade
          pip3 install setuptools --upgrade

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install package with extras
        run: |
          python -m pip install .[dev,web]

      - name: Pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Run pytest
        # Not all tests currently work on the CI. Once they do, we can simply run 'pytest'
        run: |
          pytest tests/test_config.py
          pytest tests/test_genome.py
          pytest tests/test_add_organism.py
